# Generated by Django 2.2.17 on 2020-12-25 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companymaster', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companymaster',
            old_name='AUTHORIZED_CAP',
            new_name='authorized_cap',
        ),
        migrations.RenameField(
            model_name='companymaster',
            old_name='COMPANY_CLASS',
            new_name='company_class',
        ),
        migrations.RenameField(
            model_name='companymaster',
            old_name='COMPANY_NAME',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='companymaster',
            old_name='CORPORATE_IDENTIFICATION_NUMBER',
            new_name='corporate_identification_number',
        ),
        migrations.RenameField(
            model_name='companymaster',
            old_name='DATE_OF_REGISTRATION',
            new_name='date_of_registration',
        ),
        migrations.RenameField(
            model_name='companymaster',
            old_name='PRINCIPAL_BUSINESS_ACTIVITY_AS_PER_CIN',
            new_name='principal_business_activity_as_per_cin',
        ),
    ]
